# Generated by Django 2.1.2 on 2019-02-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('Idno', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Price', models.DecimalField(decimal_places=3, max_digits=30)),
                ('Quantity', models.IntegerField()),
                ('Image', models.ImageField(upload_to='pic')),
            ],
        ),
    ]
