# Generated by Django 2.1.2 on 2019-02-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('Name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Contact', models.IntegerField()),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
    ]
